inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: disable

Style/StringLiterals:
  Enabled: false

Style/WordArray:
  Exclude:
    - db/schema.rb
