services:

  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - gem_cache:/usr/local/bundle
    env_file:
      - .envdir/development/database
      - .envdir/development/web
    depends_on:
      - database
      - redis
      - memcached
    tty: true
    stdin_open: true
    # command: /bin/bash -c 'bundle exec puma -C config/puma.rb'

  database:
    image: postgres:12.2
    env_file:
      - .envdir/development/database
    volumes:
      - db_june_backup:/var/lib/postgresql/data
      # - ./tmp/postgres:/var/lib/postgresql/data
      - .:/tmptmptmp
    ports:
      - 5432:5432

  redis:
    image: redis:5.0-alpine
    volumes:
      - redis:/data
    ports:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30

  memcached:
    image: memcached

volumes:
  gem_cache:
  db_june_backup:
  redis:
